// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusDWT3oh6q_PS5u8H9C4EUuO3C25OA-E',
    appId: '1:640779355140:web:8ba2550b65acefa9316151',
    messagingSenderId: '640779355140',
    projectId: 'erpdemo-7dfd8',
    authDomain: 'erpdemo-7dfd8.firebaseapp.com',
    storageBucket: 'erpdemo-7dfd8.appspot.com',
    measurementId: 'G-6N05YM19FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsWVwOSgduYtuPgwLjbJlEV8FaOKLywGU',
    appId: '1:640779355140:android:64f055ac2fb09c54316151',
    messagingSenderId: '640779355140',
    projectId: 'erpdemo-7dfd8',
    storageBucket: 'erpdemo-7dfd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNtIsezs6M1h1d2ZrFYPdSD3szRTa3Jw',
    appId: '1:640779355140:ios:38ab5c8219dd6856316151',
    messagingSenderId: '640779355140',
    projectId: 'erpdemo-7dfd8',
    storageBucket: 'erpdemo-7dfd8.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhNtIsezs6M1h1d2ZrFYPdSD3szRTa3Jw',
    appId: '1:640779355140:ios:38ab5c8219dd6856316151',
    messagingSenderId: '640779355140',
    projectId: 'erpdemo-7dfd8',
    storageBucket: 'erpdemo-7dfd8.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAusDWT3oh6q_PS5u8H9C4EUuO3C25OA-E',
    appId: '1:640779355140:web:e427329fc9dc3f43316151',
    messagingSenderId: '640779355140',
    projectId: 'erpdemo-7dfd8',
    authDomain: 'erpdemo-7dfd8.firebaseapp.com',
    storageBucket: 'erpdemo-7dfd8.appspot.com',
    measurementId: 'G-2Q2V224MQP',
  );
}
